"""Канонические английские названия — для словаря терминов.

Сопоставление при переводе шло через них, но в данных они не сохранялись:
оставались в голове и в комментариях. Здесь собраны и сверены по спискам
paradoxwikis, а не по памяти — расхождения находились («Violent Temper»,
а не «Rage»; «Abhors the Light», а не «Light Sensitive»).

Ключ — русское название, как оно стоит в компендиуме.
"""

POWERS = {
    # Анимализм
    "Фамулус": "Bond Famulus",
    "Чутьё на зверя": "Sense the Beast",
    "Язык животных": "Feral Whispers",
    "Зверский аппетит": "Animal Succulence",
    "Трупный улей": "Unliving Hive",
    "Усмирение зверя": "Quell the Beast",
    "Поглощение духа": "Subsume the Spirit",
    "Отчуждение зверя": "Drawing Out the Beast",
    "Царь зверей": "Animal Dominion",
    # Величие
    "Благоговение": "Awe",
    "Угроза": "Daunt",
    "Незабываемый поцелуй": "Lingering Kiss",
    "Очарование": "Entrancement",
    "Устрашающий взор": "Dread Gaze",
    "Призыв": "Summon",
    "Притягательный голос": "Irresistible Voice",
    "Звезда эфира": "Star Magnetism",
    "Преклонение": "Majesty",
    # Доминирование
    "Принуждение": "Compel",
    "Провал в памяти": "Cloud Memory",
    "Внушение": "Mesmerize",
    "Помешательство": "Dementation",
    "Внедрённая директива": "Submerged Directive",
    "Забвение": "Forgetful Mind",
    "Оправдание": "Rationalize",
    "Приказ на самоуничтожение": "Terminal Decree",
    "Стадный инстинкт": "Mass Manipulation",
    # Метаморфозы
    "Глаза зверя": "Eyes of the Beast",
    "Лёгкость пёрышка": "Weight of the Feather",
    "Оружие зверя": "Feral Weapons",
    "Слияние с землёй": "Earth Meld",
    "Смена облика": "Shapechange",
    "Перевоплощение": "Metamorphosis",
    "Превращение в туман": "Mist Form",
    "Свободное сердце": "The Unfettered Heart",
    # Мощь
    "Мощный прыжок": "Soaring Leap",
    "Смертоносность": "Lethal Body",
    "Сокрушение": "Prowess",
    "Грубое насыщение": "Brutal Feed",
    "Искра ярости": "Spark of Rage",
    "Мёртвая хватка": "Uncanny Grip",
    "Глоток могущества": "Draught of Might",
    "Землетрясение": "Earth Shock",
    "Кулак Каина": "Fist of Caine",
    # Сокрытие
    "Безмолвие смерти": "Silence of Death",
    "Плащ теней": "Cloak of Shadows",
    "Незримая поступь": "Unseen Passage",
    "Маска тысячи лиц": "Mask of a Thousand Faces",
    "Электронный призрак": "Ghost in the Machine",
    "Бесследное исчезновение": "Vanish",
    "Маскировка": "Conceal",
    "Личина самозванца": "Impostor's Guise",
    "Тайное собрание": "Cloak the Gathering",
    # Стойкость
    "Сила жизни": "Resilience",
    "Твёрдость духа": "Unswayable Mind",
    "Живучие звери": "Enduring Beasts",
    "Непрошибаемость": "Toughness",
    "Превозмогание проклятия": "Defy Bane",
    "Укрепление сознания": "Fortify the Inner Façade",
    "Глоток упорства": "Draught of Endurance",
    "Горнило боли": "Prowess from Pain",
    "Мраморная плоть": "Flesh of Marble",
    # Стремительность
    "Быстрая реакция": "Rapid Reflexes",
    "Кошачья грация": "Cat's Grace",
    "Проворство": "Fleetness",
    "Быстрее ветра": "Blink",
    "Траверс": "Traversal",
    "Безупречная точность": "Unerring Aim",
    "Глоток изящества": "Draught of Elegance",
    "Молниеносный удар": "Lightning Strike",
    "Скорость мысли": "Split Second",
    # Ясновидение
    "Обострение чувств": "Heightened Senses",
    "Потустороннее зрение": "Sense the Unseen",
    "Предвестие": "Premonition",
    "Познание души": "Scry the Soul",
    "Слияние чувств": "Share the Senses",
    "Психометрия": "Spirit's Touch",
    "Вселение": "Possession",
    "Дальновидение": "Clairvoyance",
    "Телепатия": "Telepathy",
    # Кровавое чародейство
    "Вкус крови": "A Taste for Blood",
    "Едкая кровь": "Corrosive Vitae",
    "Истончение витэ": "Extinguish Vitae",
    "Касание скорпиона": "Scorpion's Touch",
    "Сгущение крови": "Blood of Potency",
    "Хищение крови": "Theft of Vitae",
    "Котёл крови": "Cauldron of Blood",
    "Ласка Ваала": "Baal's Caress",
    # Ритуалы
    "Вечерняя бодрость": "Wake with Evening's Freshness",
    "Защитная печать от гулей": "Ward Against Ghouls",
    "Паучьи лапы": "Clinging of the Insect",
    "Постижение крови": "Blood Walk",
    "Путеводный камень": "Craft Bloodstone",
    "Защитная печать от духов": "Ward against Spirits",
    "Защитный круг от гулей": "Warding Circle against Ghouls",
    "Истина в крови": "Truth of Blood",
    "Очи вавилонские": "Eyes of Babel",
    "Свечение следопыта": "Illuminate Trail of Prey",
    "Связь с сиром": "Communicate with Kindred Sire",
    "Защитная печать от люпенов": "Ward against Lupines",
    "Защитный круг от духов": "Warding Circle against Spirits",
    "Зов Дагона": "Dagon's Call",
    "Отторжение губительного древа": "Deflection of Wooden Doom",
    "Пожиратель пламени": "Firewalker",
    "Эссенция воздуха": "Essence of Air",
    "Бесплотный путь": "Incorporeal Passage",
    "Защита неприкосновенного убежища": "Defense of the Sacred Haven",
    "Защитная печать от каинитов": "Ward against Cainites",
    "Защитный круг от люпенов": "Warding Circle against Lupines",
    "Око ночного ястреба": "Eyes of the Nighthawk",
    "Врата истинного святилища": "Escape to True Sanctuary",
    "Жало неизбежной погибели": "Shaft of Belated Dissolution",
    "Защитный круг от каинитов": "Warding Circle against Cainites",
    "Каменное сердце": "Heart of Stone",
    # Алхимия слабокровных
    "Длинные руки": "Far Reach",
    "Марево": "Haze",
    "Смог": "Envelop",
    "Нечестивая иерогамия": "Profane Hieros Gamos",
    "Восстановление крови": "Defractionate",
    "Импульс": "Airborne Momentum",
    "Будильник": "Awaken the Sleeper",
}

DISCIPLINES = {
    "Анимализм": "Animalism",
    "Величие": "Presence",
    "Доминирование": "Dominate",
    "Кровавое чародейство": "Blood Sorcery",
    "Метаморфозы": "Protean",
    "Мощь": "Potence",
    "Сокрытие": "Obfuscate",
    "Стойкость": "Fortitude",
    "Стремительность": "Celerity",
    "Ясновидение": "Auspex",
    "Ритуалы": "Blood Sorcery Rituals",
    "Алхимия слабокровных": "Thin-blood Alchemy",
    "Обливион": "Oblivion",
}

PREDATOR_TYPES = {
    "Бестия": "Blood Leech",
    "Джентльмен": "Consensualist",
    "Идол": "Osiris",
    "Искуситель": "Siren",
    "Морфей": "Sandman",
    "Налётчик": "Alleycat",
    "Семьянин": "Cleaver",
    "Суррогатчик": "Bagger",
    "Тусовщик": "Scene Queen",
    "Фермер": "Farmer",
}

BANES = {
    "Буйный нрав": "Violent Temper",
    "Изысканный вкус": "Rarefied Tastes",
    "Звериные черты": "Bestial Features",
    "Расколотое восприятие": "Fractured Perspective",
    "Отвратительность": "Repulsiveness",
    "Жажда красоты": "Aesthetic Fixation",
    "Ущербная Кровь": "Deficient Blood",
    "Кровавая зависимость": "Blood Addiction",
    "Болезненный Поцелуй": "Painful Kiss",
    "Искажённое отражение": "Distorted Image",
    "Неприятие света": "Abhors the Light",
    "Обречённость": "Doomed",
    "Гонимые": "Hunted",
    "Привязанность": "Grounded",
    "Изгой": "Outcast",
}

BANE_VARIANTS = {
    "Ядовитая кровь": "Noxious Blood",
    "Насилие": "Violence",
    "Инстинкты Выживания": "Survival Instincts",
    "Распад": "Decay",
    "Черствость": "Callousness",
    "Неестественные проявления": "Unnatural Manifestations",
    "Хладнокровный": "Cold-Blooded",
    "Заражение": "Infestation",
    "Нерожденное Имя": "Unbirth Name",
    "Аскетизм": "Asceticism",
    "Мучительное сочувствие": "Agonizing Empathy",
    "Украденная кровь": "Stolen Blood",
    "Проклятая учтивость": "Cursed Courtesy",
    "Иерархия": "Hierarchy",
}

COMPULSIONS = {
    "бунт": "Rebellion",
    "превосходство": "Arrogance",
    "животные порывы": "Feral Impulses",
    "наваждение": "Delusion",
    "криптомания": "Cryptophilia",
    "восхищение": "Obsession",
    "перфекционизм": "Perfectionism",
    "приговор": "Judgment",
    "болезненность": "Morbidity",
    "безжалостность": "Ruthlessness",
    "преступление": "Transgression",
    "искушение судьбы": "Tempting Fate",
    "аффективное сопереживание": "Affective Empathy",
    "алчность": "Covetousness",
}

STRUCTURE = {
    "Амальгама": "Amalgam",
    "Расплата": "Cost",
    "Пул": "Dice Pool",
    "Правила": "System",
    "Длительность": "Duration",
    "Компоненты": "Ingredients",
    "Изъян": "Bane",
    "Одержимость": "Compulsion",
    "Сила Крови": "Blood Potency",
    "витэ": "vitae",
    "Становление": "Embrace",
    "Сородичи": "Kindred",
    "Голод": "Hunger",
    "Человечность": "Humanity",
    "Тип охотника": "Predator Type",
}
